<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7636" started-at="2021-07-03T05:29:41Z" finished-at="2021-07-03T05:29:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7636" started-at="2021-07-03T05:29:41Z" finished-at="2021-07-03T05:29:49Z">
      <class name="test.LoginTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:test.LoginTest@7a9273a8]" name="setup" is-config="true" duration-ms="2629" started-at="2021-07-03T05:29:41Z" finished-at="2021-07-03T05:29:44Z">
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="LoginTestcase2()[pri:0, instance:test.LoginTest@7a9273a8]" name="LoginTestcase2" duration-ms="3781" started-at="2021-07-03T05:29:44Z" finished-at="2021-07-03T05:29:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<The email or password you have entered is invalid> but was:<The email or password you have entered is invalid.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<The email or password you have entered is invalid> but was:<The email or password you have entered is invalid.>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at pages.LoginPage.login(LoginPage.java:87)
	at test.LoginTest.LoginTestcase2(LoginTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1170)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1095)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
        </test-method> <!-- LoginTestcase2 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:test.LoginTest@7a9273a8]" name="teardown" is-config="true" duration-ms="334" started-at="2021-07-03T05:29:48Z" finished-at="2021-07-03T05:29:49Z">
        </test-method> <!-- teardown -->
      </class> <!-- test.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
